### ISSUE TITLE
Text disappear when finish animation

### ISSUE THREAD

**Issue by Chivorns** [totond/TextPathView#13]
How to solve this problem? It happened when text length is short.

**Comment by totond** [comment]
@Chivorns Hello , you can turn off the Hardware acceleration when using version 0.1.2

**Comment by Chivorns** [comment]
@totond : Are you sure ur library has latest commit? Cuz I run normally when I clone from ur repo.
But one more thing, Text cannot display at center of view.

**Comment by totond** [comment]
@Chivorns I am so sorry. The latest commit is not 0.1.2. I want to do something to fix the problem in  next version,  but now I am busying in my new job. I will do it as soon as possible.

**Comment by Chivorns** [comment]
got it bro! Anyway I hope u fix center in next version too.

**Comment by totond** [comment]
The version v0.2.1 has fixed the problem and turn on hardware acceleration by default.
