### ISSUE TITLE
建议增加在代码中设置属性方法

### ISSUE THREAD

**Issue by star-andy** [totond/TextPathView#4]

**Comment by totond** [comment]
你好
 - 一些关于Paint的属性设置可以使用'getDrawPaint()'和'getDrawPaint()'方法获取出来然后再设置，因为种类太多所以以这样的方式给出设置方法
 - 而duration、repeat等属性将会在下一个版本给出设置方法（目前正在开发新的输入方式，时间可能会久一点）

**Comment by star-andy** [comment]
好的  目前需要的是duration、repeat等属性，暂时在xml中设置了。
希望能增加设置其他字体样式，这样UI上能更好看些。
非常感谢

**Comment by totond** [comment]
好的，字体样式方面，后面我会研究一下TextView源码看下能不能实现的，如果有好的实现思路也欢迎提出，谢谢建议O(∩_∩)O！

**Comment by star-andy** [comment]
好的

**Comment by totond** [comment]
@qinyang1018 0.1.2版本已经可以设置字体样式啦

**Comment by star-andy** [comment]
好的  辛苦👍
